#!/bin/bash
# ============================================================
# .claude/hooks/pre_edit_guard.sh
#
# Claude Code PreToolUse Hook — intercepts Write|Edit tool calls.
# Blocks the AI from writing to sensitive / secret files.
#
# Exit 0 = allow the edit
# Exit 2 = BLOCK the edit (Claude Code specific)
# ============================================================

INPUT=$(cat)

# ── Extract the target file path from the tool input ──────
FILE=$(echo "$INPUT" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    ti = d.get('tool_input', d)
    # Claude Code sends file path in different keys depending on tool
    path = ti.get('file_path', ti.get('path', ti.get('target', '')))
    print(path)
except:
    print('')
" 2>/dev/null)

# If we couldn't extract a path, allow (fail-open for non-file edits)
[ -z "$FILE" ] && exit 0

BNAME=$(basename "$FILE")

# ── Blocked file patterns ─────────────────────────────────
BLOCKED_NAMES=(
    ".env"
    ".env.local"
    ".env.production"
    ".env.staging"
    ".env.development"
    "key.properties"
    "local.properties"
    "release.jks"
    "keystore.jks"
    "release.keystore"
    "debug.keystore"
    "google-services.json"
    "GoogleService-Info.plist"
    "env.g.dart"
    "Secret.xcconfig"
    "serviceAccountKey.json"
    "service_account.json"
    "service-account.json"
)

BLOCKED_EXTENSIONS=(
    ".jks"
    ".keystore"
    ".p12"
    ".pfx"
    ".pem"
    ".cer"
    ".crt"
)

# ── Check exact filename match ────────────────────────────
for blocked in "${BLOCKED_NAMES[@]}"; do
    if [[ "$BNAME" == "$blocked" ]]; then
        echo ""
        echo "  ✖  EDIT BLOCKED — Secret file detected"
        echo "     File: $FILE"
        echo "     Rule: AI agents must never write to '$blocked'"
        echo ""
        echo "  If this file needs updating:"
        echo "    • For .env → edit manually, then run: sh .claude/scripts/setup_secrets.sh"
        echo "    • For env.g.dart → run: dart run build_runner build"
        echo "    • For key.properties / Secret.xcconfig → auto-generated by setup_secrets.sh"
        echo ""
        exit 2
    fi
done

# ── Check blocked extensions ──────────────────────────────
for ext in "${BLOCKED_EXTENSIONS[@]}"; do
    if [[ "$BNAME" == *"$ext" ]]; then
        echo ""
        echo "  ✖  EDIT BLOCKED — Sensitive file type"
        echo "     File: $FILE"
        echo "     Rule: AI agents must never write to '*$ext' files"
        echo ""
        exit 2
    fi
done

# ── Allow everything else ─────────────────────────────────
exit 0
