#!/bin/bash
# ============================================================
# .claude/scripts/setup_ide.sh
#
# Interactive AI IDE orchestration setup.
# Generates config files ONLY for the IDE(s) the developer uses.
#
# Usage:  sh .claude/scripts/setup_ide.sh
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# ── Colors ─────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✔${NC}  $1"; }
warn() { echo -e "  ${YELLOW}!${NC}  $1"; }
skip() { echo -e "  ${DIM}–${NC}  $1 ${DIM}(skipped)${NC}"; }
fail() { echo -e "  ${RED}✖${NC}  $1"; }

# ── Paths ──────────────────────────────────────────────────
AGENTS_MD="$ROOT/AGENTS.md"
CLAUDE_MD="$ROOT/CLAUDE.md"
RULES_DIR="$ROOT/.claude/rules"
DOCS_DIR="$ROOT/.claude/docs"
MCP_SRC="$ROOT/.claude/mcp/mcp.json"
HOOKS_DIR="$ROOT/.claude/hooks"

# ── Build combined self-contained rules document ───────────
# This concatenates AGENTS.md + all .claude/rules/*.md + SECURITY.md
# into a single file that any IDE can consume without .claude/ access.
build_combined() {
    local COMBINED=$(mktemp)

    # Start with AGENTS.md
    if [ -f "$AGENTS_MD" ]; then
        # Copy AGENTS.md but replace the "Detailed References" table
        # with a note that full rules follow below
        sed '/^## Detailed References/,/^---/{
            /^## Detailed References/c\
## Detailed Rules\
\
> Full rules are inlined below. Claude Code users: these also live in `.claude/rules/` for auto-loading.
            /^---/!d
        }' "$AGENTS_MD" > "$COMBINED"
    fi

    # Append each rule file
    if [ -d "$RULES_DIR" ]; then
        for rule_file in "$RULES_DIR"/*.md; do
            [ -f "$rule_file" ] || continue
            echo "" >> "$COMBINED"
            echo "---" >> "$COMBINED"
            echo "" >> "$COMBINED"
            cat "$rule_file" >> "$COMBINED"
        done
    fi

    # Append SECURITY.md
    if [ -f "$DOCS_DIR/SECURITY.md" ]; then
        echo "" >> "$COMBINED"
        echo "---" >> "$COMBINED"
        echo "" >> "$COMBINED"
        cat "$DOCS_DIR/SECURITY.md" >> "$COMBINED"
    fi

    echo "$COMBINED"
}

# ── Copy MCP config ────────────────────────────────────────
copy_mcp() {
    local target="$1"
    local label="$2"
    if [ -f "$MCP_SRC" ]; then
        mkdir -p "$(dirname "$target")"
        cp "$MCP_SRC" "$target"
        ok "$label"
    else
        warn "MCP source (.claude/mcp/mcp.json) not found — skipped"
    fi
}

# ── Setup: Git pre-commit hook (universal) ─────────────────
setup_git_hooks() {
    local GIT_HOOKS_DIR="$ROOT/.git/hooks"
    if [ ! -d "$ROOT/.git" ]; then
        warn "Not a git repo — skipping git hooks"
        return
    fi

    mkdir -p "$GIT_HOOKS_DIR"

    cat > "$GIT_HOOKS_DIR/pre-commit" << 'HOOK'
#!/bin/bash
# Auto-generated by .claude/scripts/setup_ide.sh
# Runs secret-leak scan before every commit (any IDE, any terminal).
SCRIPT_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"
if [ -f "$SCRIPT_DIR/pre_commit.sh" ]; then
    bash "$SCRIPT_DIR/pre_commit.sh"
    exit $?
fi
exit 0
HOOK
    chmod +x "$GIT_HOOKS_DIR/pre-commit"
    ok "Git pre-commit hook → secret scan (works in ALL IDEs)"
}

# ── Setup: Claude Code ─────────────────────────────────────
setup_claude() {
    echo ""
    echo -e "  ${CYAN}Claude Code${NC}"
    echo "  ──────────"

    if [ -f "$CLAUDE_MD" ]; then
        ok "CLAUDE.md exists"
    else
        warn "CLAUDE.md not found — create it with @AGENTS.md reference"
    fi

    if [ -f "$ROOT/.claude/settings.json" ]; then
        ok ".claude/settings.json (hooks + permissions)"
    else
        warn ".claude/settings.json not found"
    fi

    copy_mcp "$ROOT/.mcp.json" ".mcp.json (MCP auto-discovery)"

    if [ -d "$HOOKS_DIR" ]; then
        ok ".claude/hooks/ (pre-edit guard, git guard, audit)"
    fi

    if [ -d "$RULES_DIR" ]; then
        ok ".claude/rules/ (auto-loaded by Claude Code)"
    fi

    echo ""
    echo -e "  ${DIM}Tip: Claude Code is your default. Everything is already wired.${NC}"
}

# ── Setup: Cursor ──────────────────────────────────────────
setup_cursor() {
    echo ""
    echo -e "  ${CYAN}Cursor${NC}"
    echo "  ──────"

    local COMBINED
    COMBINED=$(build_combined)

    # .cursorrules (single file — legacy format, some versions prefer this)
    cp "$COMBINED" "$ROOT/.cursorrules"
    ok ".cursorrules (combined rules)"

    # .cursor/rules/ (individual files — newer Cursor format)
    mkdir -p "$ROOT/.cursor/rules"
    cp "$COMBINED" "$ROOT/.cursor/rules/flutter_rules.md"
    ok ".cursor/rules/flutter_rules.md"

    # MCP
    copy_mcp "$ROOT/.cursor/mcp.json" ".cursor/mcp.json (MCP for Cursor)"

    rm -f "$COMBINED"
}

# ── Setup: Windsurf ────────────────────────────────────────
setup_windsurf() {
    echo ""
    echo -e "  ${CYAN}Windsurf${NC}"
    echo "  ────────"

    local COMBINED
    COMBINED=$(build_combined)
    cp "$COMBINED" "$ROOT/.windsurfrules"
    ok ".windsurfrules (combined rules)"
    rm -f "$COMBINED"
}

# ── Setup: VS Code Copilot ─────────────────────────────────
setup_copilot() {
    echo ""
    echo -e "  ${CYAN}VS Code Copilot${NC}"
    echo "  ───────────────"

    local COMBINED
    COMBINED=$(build_combined)

    mkdir -p "$ROOT/.github"
    cp "$COMBINED" "$ROOT/.github/copilot-instructions.md"
    ok ".github/copilot-instructions.md"

    # MCP for VS Code
    copy_mcp "$ROOT/.vscode/mcp.json" ".vscode/mcp.json (MCP for VS Code)"

    rm -f "$COMBINED"
}

# ── Setup: Gemini CLI / Antigravity ────────────────────────
setup_gemini() {
    echo ""
    echo -e "  ${CYAN}Gemini CLI / Antigravity${NC}"
    echo "  ────────────────────────"

    local COMBINED
    COMBINED=$(build_combined)
    cp "$COMBINED" "$ROOT/GEMINI.md"
    ok "GEMINI.md (combined rules)"
    rm -f "$COMBINED"

    echo ""
    echo -e "  ${DIM}Note: Antigravity can also read .claude/ files when exploring,${NC}"
    echo -e "  ${DIM}but GEMINI.md ensures rules are always in context.${NC}"
}

# ── Setup: Codex / Aider ──────────────────────────────────
setup_codex() {
    echo ""
    echo -e "  ${CYAN}OpenAI Codex / Aider${NC}"
    echo "  ─────────────────────"

    local COMBINED
    COMBINED=$(build_combined)

    # These IDEs read AGENTS.md — we must make it self-contained
    cp "$COMBINED" "$ROOT/AGENTS.md"
    ok "AGENTS.md (made self-contained with all rules inlined)"

    rm -f "$COMBINED"

    echo ""
    echo -e "  ${YELLOW}!${NC}  AGENTS.md is now self-contained (rules inlined)."
    echo -e "     Claude Code still works — it has CLAUDE.md + .claude/rules/ separately."
}

# ── Setup: Universal git hooks ─────────────────────────────
prompt_git_hooks() {
    echo ""
    echo -e "  ${CYAN}Universal Git Hooks${NC}"
    echo "  ───────────────────"
    echo ""
    echo "  Claude Code has built-in security hooks (.claude/hooks/)."
    echo "  Want to ALSO install a git pre-commit hook so the secret"
    echo "  scanner runs in ANY IDE / terminal?"
    echo ""
    echo -n "  Install git pre-commit hook? [Y/n]: "
    read -r GIT_ANSWER
    GIT_ANSWER=${GIT_ANSWER:-Y}

    if [[ "$GIT_ANSWER" =~ ^[Yy] ]]; then
        setup_git_hooks
    else
        skip "Git pre-commit hook"
    fi
}

# ── Add generated files to .gitignore ──────────────────────
update_gitignore() {
    local GITIGNORE="$ROOT/.gitignore"
    local MARKER="# AI IDE sync targets (generated by setup_ide.sh)"

    # Skip if marker already exists
    if [ -f "$GITIGNORE" ] && grep -qF "$MARKER" "$GITIGNORE"; then
        return
    fi

    echo "" >> "$GITIGNORE"
    cat >> "$GITIGNORE" << 'EOF'
# AI IDE sync targets (generated by setup_ide.sh)
GEMINI.md
.windsurfrules
.cursorrules
.cursor/rules/
.cursor/mcp.json
.vscode/mcp.json
.github/copilot-instructions.md
EOF
    ok ".gitignore updated (sync targets excluded from git)"
}

# ═══════════════════════════════════════════════════════════
# MAIN — Interactive menu
# ═══════════════════════════════════════════════════════════

echo ""
echo -e "  ${BOLD}Flutter AI Agent — IDE Setup${NC}"
echo "  ═══════════════════════════════════"
echo ""
echo "  Your project has AI orchestration rules in .claude/"
echo "  This script generates config files for your IDE."
echo ""
echo "  Which IDE do you use?"
echo ""
echo -e "  ${GREEN}1${NC})  Claude Code          ${DIM}(default — already configured)${NC}"
echo -e "  ${GREEN}2${NC})  Cursor"
echo -e "  ${GREEN}3${NC})  Windsurf"
echo -e "  ${GREEN}4${NC})  VS Code Copilot"
echo -e "  ${GREEN}5${NC})  Gemini CLI / Antigravity"
echo -e "  ${GREEN}6${NC})  OpenAI Codex / Aider"
echo -e "  ${GREEN}7${NC})  All of the above"
echo -e "  ${GREEN}0${NC})  Exit"
echo ""
echo -n "  Choose [1-7, or comma-separated e.g. 1,2,5]: "
read -r CHOICES

# Default to Claude Code
CHOICES=${CHOICES:-1}

# Normalize: strip spaces, handle "all"
CHOICES=$(echo "$CHOICES" | tr -d ' ')

# Expand "7" to all
if [[ "$CHOICES" == "7" ]]; then
    CHOICES="1,2,3,4,5,6"
fi

# Exit
if [[ "$CHOICES" == "0" ]]; then
    echo ""
    echo "  Exited. No changes made."
    echo ""
    exit 0
fi

echo ""
echo "  Setting up..."
echo "  ──────────────"

# Parse comma-separated choices
IFS=',' read -ra SELECTED <<< "$CHOICES"

for choice in "${SELECTED[@]}"; do
    case "$choice" in
        1) setup_claude ;;
        2) setup_cursor ;;
        3) setup_windsurf ;;
        4) setup_copilot ;;
        5) setup_gemini ;;
        6) setup_codex ;;
        *) warn "Unknown option: $choice" ;;
    esac
done

# Always offer git hooks
prompt_git_hooks

# Update .gitignore for generated files
echo ""
update_gitignore

echo ""
echo "  ═══════════════════════════════════"
echo -e "  ${GREEN}Done.${NC} Your IDE is ready."
echo ""
echo -e "  ${DIM}• Restart your IDE for MCP changes to take effect.${NC}"
echo -e "  ${DIM}• Re-run this script anytime: sh .claude/scripts/setup_ide.sh${NC}"
echo ""
